name: Test SSH Connection

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Test SSH Connection
        env:
          PRIVATE_KEY: ${{ secrets.EC2_KEY }}
          HOST: ${{ secrets.EC2_IP }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          echo "Testing connection to ${USER}@${HOST}"
          ssh -vvv -o StrictHostKeyChecking=no -i private_key.pem ${USER}@${HOST} 'echo "Connection successful!"'
          rm -f private_key.pem
